spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todolist?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
    open-in-view: true